"use client";

import { useEffect, useState } from "react";
import confetti from "canvas-confetti";

interface Question {
  question: string;
  options: { id: string; text: string }[];
  correct_option: string;
  explanation: string;
}

interface QuizSubmissionProps {
  taskId: string;
  goalId: string;
  taskTitle: string;
  taskDescription?: string;
  onSuccess: () => void;
}

export default function QuizSubmission({
  taskId,
  goalId,
  taskTitle,
  taskDescription,
  onSuccess,
}: QuizSubmissionProps) {
  const [started, setStarted] = useState<boolean>(false);
  const [loadingQuestions, setLoadingQuestions] = useState<boolean>(false);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIndex, setCurrentIndex] = useState<number>(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>({});
  const [submitting, setSubmitting] = useState<boolean>(false);
  const [quizResult, setQuizResult] = useState<{
    score: number;
    passed: boolean;
    correctCount: number;
  } | null>(null);

  const startQuiz = async () => {
    setLoadingQuestions(true);
    try {
      const res = await fetch("/api/verify/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "generate",
          taskId,
          goalId,
          topicTitle: taskTitle,
          topicDescription: taskDescription,
        }),
      });

      const data = await res.json();
      if (res.ok && data.questions) {
        setQuestions(data.questions);
        setStarted(true);
      }
    } catch (e) {
      console.error("Failed to load questions:", e);
    } finally {
      setLoadingQuestions(false);
    }
  };

  const handleSelectOption = (optionId: string) => {
    setSelectedAnswers({
      ...selectedAnswers,
      [currentIndex]: optionId,
    });
  };

  const handleNextQuestion = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(currentIndex + 1);
    } else {
      submitQuizResults();
    }
  };

  const submitQuizResults = async () => {
    setSubmitting(true);
    try {
      let correctCount = 0;
      questions.forEach((q, idx) => {
        if (selectedAnswers[idx] === q.correct_option) {
          correctCount++;
        }
      });

      const scorePct = Math.round((correctCount / questions.length) * 100);
      const passed = scorePct >= 60;

      const res = await fetch("/api/verify/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "evaluate",
          taskId,
          goalId,
          score: scorePct,
          passed,
        }),
      });

      setQuizResult({
        score: scorePct,
        passed,
        correctCount,
      });

      if (passed) {
        confetti({
          particleCount: 100,
          spread: 70,
          origin: { y: 0.6 },
          colors: ["#4a7c59", "#78a886", "#c4a66a"],
        });
        setTimeout(() => {
          onSuccess();
        }, 2500);
      }
    } catch (e) {
      console.error("Error evaluating quiz:", e);
    } finally {
      setSubmitting(false);
    }
  };

  if (!started) {
    return (
      <div className="bg-surface-container-lowest p-8 md:p-12 rounded-[2rem] border border-outline-variant/30 shadow-organic max-w-2xl mx-auto text-center flex flex-col items-center gap-6">
        <div className="w-16 h-16 bg-primary-container rounded-2xl flex items-center justify-center text-on-primary-container">
          <span className="material-symbols-outlined text-3xl filled">
            quiz
          </span>
        </div>

        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-primary bg-primary-fixed/40 px-3.5 py-1 rounded-full">
            Knowledge Verification
          </span>
          <h2 className="font-headline text-3xl font-bold text-on-surface mt-3">
            {taskTitle}
          </h2>
          <p className="text-on-surface-variant text-sm mt-2 max-w-md leading-relaxed">
            {taskDescription || "Complete a 5-question multiple choice test based on your committed study topic."}
          </p>
        </div>

        <div className="bg-surface-container p-5 rounded-2xl border border-outline-variant/20 w-full text-left space-y-2 text-xs text-on-surface-variant">
          <div className="flex items-center gap-2 text-on-surface font-semibold">
            <span className="material-symbols-outlined text-primary text-base">
              info
            </span>
            Quiz Protocol Rules
          </div>
          <p>• 5 multiple choice questions generated by AI</p>
          <p>• Passing score: ≥ 60% (at least 3 correct answers)</p>
          <p>• Instant 100% stake refund upon passing</p>
          <p>• 1 retry allowed after 24 hours if you score under 60%</p>
        </div>

        <button
          onClick={startQuiz}
          disabled={loadingQuestions}
          className="bg-primary hover:bg-primary/90 text-on-primary font-headline font-bold text-lg px-10 py-4 rounded-xl shadow-organic transition-all active:scale-95 cursor-pointer disabled:opacity-50 flex items-center gap-2"
        >
          {loadingQuestions ? (
            <>
              <span className="material-symbols-outlined animate-spin text-xl">
                progress_activity
              </span>
              Generating Questions...
            </>
          ) : (
            <>
              Start Quiz
              <span className="material-symbols-outlined text-xl">
                arrow_forward
              </span>
            </>
          )}
        </button>
      </div>
    );
  }

  if (quizResult) {
    return (
      <div className="bg-surface-container-lowest p-8 md:p-12 rounded-[2rem] border border-outline-variant/30 shadow-organic max-w-xl mx-auto text-center flex flex-col items-center gap-6">
        <div
          className={`w-20 h-20 rounded-full flex items-center justify-center text-4xl shadow-inner ${
            quizResult.passed
              ? "bg-primary-container text-on-primary-container"
              : "bg-error-container text-on-error-container"
          }`}
        >
          <span className="material-symbols-outlined text-4xl filled">
            {quizResult.passed ? "check_circle" : "cancel"}
          </span>
        </div>

        <div>
          <h2 className="font-headline text-3xl font-bold text-on-surface">
            {quizResult.passed ? "Verification Passed!" : "Score Below Threshold"}
          </h2>
          <p className="text-on-surface-variant text-sm mt-2">
            You scored{" "}
            <strong className="text-on-surface text-base">
              {quizResult.score}%
            </strong>{" "}
            ({quizResult.correctCount} of {questions.length} correct)
          </p>
        </div>

        <div
          className={`p-5 rounded-2xl text-xs text-left w-full ${
            quizResult.passed
              ? "bg-primary-fixed/40 text-on-primary-fixed border border-primary/30"
              : "bg-surface-container text-on-surface-variant border border-outline-variant/30"
          }`}
        >
          {quizResult.passed
            ? "✅ Your milestone has been verified and your stake refund is now processed back to your payment account."
            : "❌ A passing score of 60% was required. You may attempt this quiz one more time after 24 hours of further review."}
        </div>
      </div>
    );
  }

  const currentQ = questions[currentIndex];
  const currentSelected = selectedAnswers[currentIndex];

  return (
    <div className="bg-surface-container-lowest p-8 md:p-10 rounded-[2rem] border border-outline-variant/30 shadow-organic max-w-2xl mx-auto flex flex-col gap-8">
      {/* Quiz Progress header */}
      <div className="flex justify-between items-center text-xs font-bold uppercase tracking-wider text-on-surface-variant">
        <span>
          Question {currentIndex + 1} of {questions.length}
        </span>
        <span className="text-primary">Passing Threshold: 60%</span>
      </div>

      <div className="w-full bg-surface-container-highest rounded-full h-2 overflow-hidden">
        <div
          className="bg-primary h-full rounded-full transition-all duration-300"
          style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
        />
      </div>

      {/* Question Text */}
      <div>
        <h3 className="font-headline text-2xl font-bold text-on-surface leading-snug">
          {currentQ.question}
        </h3>
      </div>

      {/* Options */}
      <div className="space-y-3">
        {currentQ.options.map((opt) => {
          const isSelected = currentSelected === opt.id;
          return (
            <div
              key={opt.id}
              onClick={() => handleSelectOption(opt.id)}
              className={`p-5 rounded-2xl border-2 transition-all cursor-pointer flex items-center gap-4 ${
                isSelected
                  ? "border-primary bg-primary-fixed/20 shadow-sm"
                  : "border-outline-variant/30 bg-surface hover:border-outline-variant"
              }`}
            >
              <span
                className={`w-8 h-8 rounded-xl text-xs font-bold flex items-center justify-center shrink-0 ${
                  isSelected
                    ? "bg-primary text-on-primary"
                    : "bg-surface-container text-on-surface-variant"
                }`}
              >
                {opt.id}
              </span>
              <span className="font-body text-sm font-semibold text-on-surface">
                {opt.text}
              </span>
            </div>
          );
        })}
      </div>

      {/* Action CTA */}
      <button
        onClick={handleNextQuestion}
        disabled={!currentSelected || submitting}
        className="w-full bg-primary hover:bg-primary/90 text-on-primary font-headline font-bold text-lg py-4 rounded-xl shadow-organic transition-all active:scale-[0.98] cursor-pointer disabled:opacity-40 flex items-center justify-center gap-2"
      >
        {submitting ? (
          <>
            <span className="material-symbols-outlined animate-spin text-xl">
              progress_activity
            </span>
            Scoring Quiz...
          </>
        ) : currentIndex === questions.length - 1 ? (
          <>
            Complete & Evaluate
            <span className="material-symbols-outlined text-xl">
              check_circle
            </span>
          </>
        ) : (
          <>
            Next Question
            <span className="material-symbols-outlined text-xl">
              arrow_forward
            </span>
          </>
        )}
      </button>
    </div>
  );
}
